# This rule is not used by the project dynamic-prefix-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dynamic-prefix.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dynamic-prefix-operator
    app.kubernetes.io/managed-by: kustomize
  name: dynamicprefix-admin-role
rules:
- apiGroups:
  - dynamic-prefix.io
  resources:
  - dynamicprefixes
  verbs:
  - '*'
- apiGroups:
  - dynamic-prefix.io
  resources:
  - dynamicprefixes/status
  verbs:
  - get
