{{- if .Values.config.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamic-prefix-operator.fullname" . }}-metrics
  labels:
    {{- include "dynamic-prefix-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "dynamic-prefix-operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
